name: Public IP

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}

    - name: Get IPv4
      run: |
        echo ::set-env name=IPv4::$( curl https://api.ipify.org )

    - name: Set Allowed_SOurces
      run: |
        echo ::set-env name=ALLOWED_SOURCES::${IPv4}/32

    - name: Build
      run: |
         echo "$ALLOWED_SOURCES"