name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: true
    - run: echo runs on success
      if: ${{ success() }}
    - run: false
    - run: echo runs on failure
      if: ${{ failure() }}
    - run: echo runs on success
      if: ${{ success() }}
    - run: echo runs on failure
      if: ${{ failure() }}
    - run: echo runs always, even if the prior step was canceled
      if: always()

